# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01b028910b5ab96bbf3e52f56a713a0ec96beb243e3d4575103dc3d8a7c23fcc29af5342fd0c6ce276dae022a2938539439cfe14df8e6774eefcd1705fbf9299

test:
  secret_key_base: 74ab438d1056fa1a7028ef06dc45b264c3b46390e75e22b4c6811e00b1c94edef036a7729c8d369a608cbaef03c2595b0cc78571345e12125574a605cbfdff03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
